require File.dirname(__FILE__) + '/scatter/commands/list'
require File.dirname(__FILE__) + '/scatter/commands/push'
require File.dirname(__FILE__) + '/scatter/commands/receive'
require File.dirname(__FILE__) + '/scatter/config'
require File.dirname(__FILE__) + '/scatter/logger'
require File.dirname(__FILE__) + '/scatter/node'
require File.dirname(__FILE__) + '/scatter/remote'
